#!/usr/bin/env python3
from __future__ import annotations

import argparse
import datetime
import json
import math
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


DEFAULT_PER_BANDS = {
    5: (None, 8.0),
    4: (8.0, 9.0),
    3: (9.0, 10.0),
    2: (10.0, 11.0),
    1: (11.0, None),
}


@dataclass(frozen=True)
class Scenario:
    label: str
    eps: float


@dataclass(frozen=True)
class PriceHistorySummary:
    start_date: str
    end_date: str
    trading_days: int
    close_low: float
    close_high: float
    latest_close: float
    latest_close_date: str
    range_position_pct: float
    percentile_pct: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Taiwan stock valuation bands and 1-5 score ranges from an analysis JSON."
    )
    parser.add_argument("--analysis-json", type=Path, help="Path to *_analysis.json")
    parser.add_argument(
        "--stock-id",
        help="Stock ID used to run an explicit analyze script before valuation",
    )
    parser.add_argument(
        "--analyze-script",
        type=Path,
        help="Path to analyze_tw_stock.py; no default because this repo does not include it",
    )
    parser.add_argument(
        "--current-price",
        type=float,
        help="Current market price for scenario scoring",
    )
    parser.add_argument(
        "--price-history-json",
        type=Path,
        help="Path to <stock_id>_<market>_price_history.json generated by fetch_price_history.py",
    )
    parser.add_argument(
        "--output-format",
        choices=("md", "json"),
        default="md",
        help="Report format：md（預設，寫入 Obsidian 當前開啟的筆記）｜json",
    )
    parser.add_argument(
        "--output-file",
        type=Path,
        help="Write the report to a specific file path",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="Write the report into a directory; filename is derived from analysis JSON",
    )
    parser.add_argument(
        "--vault-root",
        type=Path,
        default=Path("."),
        help="Obsidian Vault 根目錄（md 格式偵測當前開啟檔用），預設當前目錄",
    )
    parser.add_argument(
        "--note-path",
        help="自訂 Obsidian 筆記路徑（相對 --vault-root）；省略＝寫入當前開啟的檔案（僅 md 格式）",
    )
    parser.add_argument(
        "--write-mode",
        choices=("overwrite", "append", "newfile"),
        default="overwrite",
        help="md 寫入模式：overwrite（複寫，預設）｜append（附加，去重 frontmatter）｜newfile（建立新檔，自動改名）",
    )
    parser.add_argument("--pessimistic-eps", type=float, help="Override pessimistic EPS")
    parser.add_argument("--base-eps", type=float, help="Override base EPS")
    parser.add_argument("--optimistic-eps", type=float, help="Override optimistic EPS")
    parser.add_argument(
        "--scenario-downside",
        type=float,
        default=0.15,
        help="Default downside ratio vs base EPS",
    )
    parser.add_argument(
        "--scenario-upside",
        type=float,
        default=0.15,
        help="Default upside ratio vs base EPS",
    )
    parser.add_argument(
        "--precision",
        type=int,
        default=2,
        help="Decimal precision for EPS",
    )
    return parser.parse_args()


def run_analysis(stock_id: str, analyze_script: Path) -> Path:
    if not analyze_script.exists():
        raise FileNotFoundError(f"找不到分析腳本：{analyze_script}")

    result = subprocess.run(
        [sys.executable, str(analyze_script), stock_id],
        check=True,
        capture_output=True,
        text=True,
    )
    payload = json.loads(result.stdout)
    return Path(payload["json_path"])


def load_analysis_json(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(f"找不到分析 JSON：{path}")
    return json.loads(path.read_text(encoding="utf-8"))


def load_price_history_json(path: Path | None, stock_id: str | None) -> PriceHistorySummary | None:
    if path is None:
        return None
    if not path.exists():
        raise FileNotFoundError(f"找不到歷史股價 JSON：{path}")
    payload = json.loads(path.read_text(encoding="utf-8"))
    history_stock_id = payload.get("stock_id")
    if stock_id and history_stock_id and stock_id != history_stock_id:
        raise ValueError(
            f"歷史股價 JSON 股票代號不一致：analysis={stock_id} price_history={history_stock_id}"
        )
    summary = payload.get("summary") or {}
    required_keys = {
        "start_date",
        "end_date",
        "trading_days",
        "close_low",
        "close_high",
        "latest_close",
        "latest_close_date",
        "range_position_pct",
        "percentile_pct",
    }
    missing = required_keys - set(summary)
    if missing:
        raise ValueError(f"歷史股價 JSON 缺少 summary 欄位：{', '.join(sorted(missing))}")
    return PriceHistorySummary(
        start_date=summary["start_date"],
        end_date=summary["end_date"],
        trading_days=int(summary["trading_days"]),
        close_low=float(summary["close_low"]),
        close_high=float(summary["close_high"]),
        latest_close=float(summary["latest_close"]),
        latest_close_date=summary["latest_close_date"],
        range_position_pct=float(summary["range_position_pct"]),
        percentile_pct=float(summary["percentile_pct"]),
    )


def latest_year_payload(data: dict) -> tuple[str, dict]:
    years = data.get("years") or []
    if not years:
        raise ValueError("analysis JSON 缺少 years")
    year = years[-1]
    return year, data["metrics_by_year"][year]


def resolve_base_eps(data: dict) -> tuple[float, str]:
    """基準 EPS：優先 TTM（最近四季，更即時），無則退回最新年報 EPS。"""
    ttm = data.get("ttm") or {}
    ttm_eps = ttm.get("eps")
    if ttm_eps not in (None, 0) and ttm_eps > 0:
        return float(ttm_eps), f"TTM｜{ttm.get('basis', '最近四季')}"
    year, latest = latest_year_payload(data)
    latest_eps = latest.get("eps")
    if latest_eps in (None, 0):
        raise ValueError(f"{data.get('stock_id')} 最新年度 EPS 不可用")
    return float(latest_eps), f"{year} 年報 EPS"


def round_price(value: float | None) -> float | None:
    if value is None:
        return None
    return round(value, 2)


def build_scenarios(args: argparse.Namespace, latest_eps: float) -> list[Scenario]:
    precision = max(args.precision, 0)
    base_eps = args.base_eps if args.base_eps is not None else latest_eps
    pessimistic = (
        args.pessimistic_eps
        if args.pessimistic_eps is not None
        else round(base_eps * (1 - args.scenario_downside), precision)
    )
    optimistic = (
        args.optimistic_eps
        if args.optimistic_eps is not None
        else round(base_eps * (1 + args.scenario_upside), precision)
    )
    return [
        Scenario("悲觀", round(pessimistic, precision)),
        Scenario("中性", round(base_eps, precision)),
        Scenario("樂觀", round(optimistic, precision)),
    ]


def build_price_bands(eps: float) -> list[dict]:
    bands: list[dict] = []
    for score, (lower_per, upper_per) in DEFAULT_PER_BANDS.items():
        lower_price = None if lower_per is None else round_price(lower_per * eps)
        upper_price = None if upper_per is None else round_price(upper_per * eps)
        if score == 5:
            price_range = f"{fmt_price(upper_price)} 以下"
        elif score == 1:
            price_range = f"{fmt_price(lower_price)} 以上"
        else:
            price_range = f"{fmt_price(lower_price)}–{fmt_price(upper_price)}"
        bands.append(
            {
                "score": score,
                "per_low": lower_per,
                "per_high": upper_per,
                "price_low": lower_price,
                "price_high": upper_price,
                "price_range": price_range,
            }
        )
    return bands


def score_price(price: float, eps: float) -> dict:
    per = price / eps if eps else math.inf
    if per < 8:
        score = 5
    elif per < 9:
        score = 4
    elif per < 10:
        score = 3
    elif per < 11:
        score = 2
    else:
        score = 1
    return {
        "price": round_price(price),
        "per": round(per, 2),
        "score": score,
    }


def allocation_for_score(score: int) -> str:
    mapping = {
        5: "可積極看待",
        4: "可分批布局",
        3: "正常持有",
        2: "追價保守",
        1: "需更強成長支撐",
    }
    return mapping[score]


def fmt_price(value: float | None) -> str:
    if value is None:
        return "-"
    if abs(value - round(value)) < 1e-9:
        return str(int(round(value)))
    return f"{value:.2f}"


def fmt_per(value: float | None) -> str:
    if value is None:
        return "-"
    return f"{value:.2f}x"


def fmt_metric(value: float | None, digits: int = 2, suffix: str = "") -> str:
    if value is None:
        return "-"
    return f"{value:.{digits}f}{suffix}"


def metric_delta(values: list[float | None], digits: int = 2, suffix: str = "") -> str:
    usable = [value for value in values if value is not None]
    if len(usable) < 2:
        return "資料不足"
    delta = usable[-1] - usable[0]
    sign = "+" if delta > 0 else ""
    return f"{sign}{delta:.{digits}f}{suffix}"


def trend_text(values: list[float | None], positive_is_good: bool = True) -> str:
    usable = [value for value in values if value is not None]
    if len(usable) < 2:
        return "資料不足"
    if usable[-1] > usable[0]:
        return "改善" if positive_is_good else "升高"
    if usable[-1] < usable[0]:
        return "轉弱" if positive_is_good else "下降"
    return "持平"


def derive_output_path(
    analysis_json: Path,
    output_format: str,
    output_file: Path | None,
    output_dir: Path | None,
) -> Path:
    if output_file is not None:
        return output_file

    suffix = {"json": ".json", "md": ".md"}.get(output_format, ".md")
    stem = analysis_json.stem
    if stem.endswith("_analysis"):
        report_name = f"{stem[:-9]}_valuation{suffix}"
    else:
        report_name = f"{stem}_valuation{suffix}"

    base_dir = output_dir if output_dir is not None else analysis_json.parent
    return base_dir / report_name


def write_report(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


def financial_row(
    label: str,
    values: list[float | None],
    digits: int = 2,
    suffix: str = "",
    trend: str | None = None,
    positive_is_good: bool = True,
) -> dict:
    rendered_trend = trend if trend is not None else metric_delta(values, digits, suffix)
    status = trend_text(values, positive_is_good)
    if status == "改善":
        trend_class_name = "up"
    elif status in {"轉弱", "升高"}:
        trend_class_name = "down"
    else:
        trend_class_name = "neutral"
    return {
        "label": label,
        "values": [fmt_metric(value, digits, suffix) for value in values],
        "trend": rendered_trend,
        "trend_class": trend_class_name,
    }


def describe_range_position(range_position_pct: float) -> str:
    if range_position_pct <= 20:
        return "接近區間低檔"
    if range_position_pct <= 40:
        return "偏低檔"
    if range_position_pct <= 60:
        return "位於區間中段"
    if range_position_pct <= 80:
        return "偏高檔"
    return "接近區間高檔"


def build_financial_groups(data: dict) -> list[dict]:
    years = data.get("years") or []
    metrics_by_year = data.get("metrics_by_year") or {}
    if not years or not metrics_by_year:
        return []

    metrics = [metrics_by_year.get(year, {}) for year in years]

    revenue_values = [metric.get("revenue") for metric in metrics]
    gross_margin_values = [metric.get("gross_margin") for metric in metrics]
    total_opex_ratio_values = [metric.get("total_opex_ratio") for metric in metrics]
    op_margin_values = [metric.get("op_margin") for metric in metrics]
    net_income_values = [metric.get("net_income") for metric in metrics]
    eps_values = [metric.get("eps") for metric in metrics]
    roe_values = [metric.get("roe") for metric in metrics]
    dividends_values = [
        None if metric.get("dividends") is None else abs(metric.get("dividends"))
        for metric in metrics
    ]
    cash_values = [metric.get("cash") for metric in metrics]
    current_ratio_values = [metric.get("current_ratio") for metric in metrics]
    debt_ratio_values = [metric.get("debt_ratio") for metric in metrics]
    operating_cf_values = [metric.get("operating_cf") for metric in metrics]
    fcf_values = [metric.get("fcf") for metric in metrics]
    cfo_to_net_values = [metric.get("cfo_to_net") for metric in metrics]

    return [
        {
            "title": "營運規模與成本結構",
            "rows": [
                financial_row("營收（億元）", revenue_values, trend=f"{trend_text(revenue_values)} {metric_delta(revenue_values)} 億元"),
                financial_row("毛利率", gross_margin_values, suffix="%", trend=f"{trend_text(gross_margin_values)} {metric_delta(gross_margin_values, suffix='%')}"),
                financial_row(
                    "營業費用率",
                    total_opex_ratio_values,
                    suffix="%",
                    trend=f"{trend_text(total_opex_ratio_values, positive_is_good=False)} {metric_delta(total_opex_ratio_values, suffix='%')}",
                    positive_is_good=False,
                ),
                financial_row("營業利益率", op_margin_values, suffix="%", trend=f"{trend_text(op_margin_values)} {metric_delta(op_margin_values, suffix='%')}"),
            ],
        },
        {
            "title": "獲利與股東報酬",
            "rows": [
                financial_row("稅後淨利（億元）", net_income_values, trend=f"{trend_text(net_income_values)} {metric_delta(net_income_values)} 億元"),
                financial_row("EPS（元）", eps_values, trend=f"{trend_text(eps_values)} {metric_delta(eps_values)} 元"),
                financial_row("ROE", roe_values, suffix="%", trend=f"{trend_text(roe_values)} {metric_delta(roe_values, suffix='%')}"),
                financial_row("現金股利（億元）", dividends_values, trend=f"{trend_text(dividends_values)} {metric_delta(dividends_values)} 億元"),
            ],
        },
        {
            "title": "資產負債與現金流",
            "rows": [
                financial_row("現金部位（億元）", cash_values, trend=f"{trend_text(cash_values)} {metric_delta(cash_values)} 億元"),
                financial_row("流動比率", current_ratio_values, suffix="%", trend=f"{trend_text(current_ratio_values)} {metric_delta(current_ratio_values, suffix='%')}"),
                financial_row(
                    "負債比率",
                    debt_ratio_values,
                    suffix="%",
                    trend=f"{trend_text(debt_ratio_values, positive_is_good=False)} {metric_delta(debt_ratio_values, suffix='%')}",
                    positive_is_good=False,
                ),
                financial_row("營業現金流（億元）", operating_cf_values, trend=f"{trend_text(operating_cf_values)} {metric_delta(operating_cf_values)} 億元"),
                financial_row("自由現金流（億元）", fcf_values, trend=f"{trend_text(fcf_values)} {metric_delta(fcf_values)} 億元"),
                financial_row("現金流/淨利", cfo_to_net_values, trend=f"{trend_text(cfo_to_net_values)} {metric_delta(cfo_to_net_values)} 倍"),
            ],
        },
    ]


def make_report(
    data: dict,
    scenarios: list[Scenario],
    current_price: float | None,
    price_history: PriceHistorySummary | None,
) -> dict:
    year, latest = latest_year_payload(data)
    company = data.get("company_name", data.get("stock_id", ""))
    stock_id = data.get("stock_id", "")
    _, base_basis = resolve_base_eps(data)
    # 報告顯示的基準 EPS 取自中性情境（即實際驅動估值帶的值），與 scenarios 一致
    base_eps_value = next((s.eps for s in scenarios if s.label == "中性"), scenarios[0].eps)

    scenario_rows = []
    for scenario in scenarios:
        bands = build_price_bands(scenario.eps)
        current = score_price(current_price, scenario.eps) if current_price is not None else None
        scenario_rows.append(
            {
                "label": scenario.label,
                "eps": scenario.eps,
                "bands": bands,
                "current_price_view": current,
            }
        )

    return {
        "company_name": company,
        "stock_id": stock_id,
        "latest_year": year,
        "latest_eps": base_eps_value,
        "base_eps_basis": base_basis,
        "analysis_data": data,
        "current_price": current_price,
        "price_history_summary": None
        if price_history is None
        else {
            "start_date": price_history.start_date,
            "end_date": price_history.end_date,
            "trading_days": price_history.trading_days,
            "close_low": price_history.close_low,
            "close_high": price_history.close_high,
            "latest_close": price_history.latest_close,
            "latest_close_date": price_history.latest_close_date,
            "range_position_pct": price_history.range_position_pct,
            "percentile_pct": price_history.percentile_pct,
            "range_position_label": describe_range_position(price_history.range_position_pct),
        },
        "scenario_rows": scenario_rows,
    }


def per_range_text(band: dict) -> str:
    low = fmt_per(band["per_low"])
    high = fmt_per(band["per_high"])
    if band["score"] == 5:
        return f"{high} 以下"
    if band["score"] == 1:
        return f"{low} 以上"
    return f"{low}–{high}"


def render_markdown(report: dict) -> str:
    company = report["company_name"]
    stock_id = report["stock_id"]
    year = report["latest_year"]
    latest_eps = report["latest_eps"]
    base_basis = report.get("base_eps_basis", "最新年報")
    history = report.get("price_history_summary")
    current_price = report["current_price"]
    years = report["analysis_data"].get("years") or []
    financial_groups = build_financial_groups(report["analysis_data"])
    today = datetime.date.today().isoformat()

    neutral = next(
        (scenario for scenario in report["scenario_rows"] if scenario["label"] == "中性"),
        report["scenario_rows"][0],
    )
    neutral_current = neutral["current_price_view"]
    neutral_band = next((band for band in neutral["bands"] if band["score"] == 3), None)
    neutral_range = neutral_band["price_range"] if neutral_band else "-"
    current_score_text = f"{neutral_current['score']} 分" if neutral_current else "未提供現價"

    lines: list[str] = []
    lines.append("---")
    lines.append(f"ticker: {stock_id}")
    lines.append(f"name: {company}")
    lines.append("type: 個股")
    lines.append("report: 估值區間")
    lines.append("source: analysis JSON")
    lines.append(f"latest_year: {year}")
    lines.append(f"base_eps: {latest_eps:.2f}")
    lines.append(f"current_price: {fmt_price(current_price) if current_price is not None else '-'}")
    lines.append(f"current_score: {current_score_text}")
    lines.append(f"last_updated: {today}")
    lines.append("---")
    lines.append("")
    lines.append(f"# {company}（{stock_id}）估值區間報告")
    lines.append("")

    # 基本資訊
    lines.append("## 基本資訊")
    lines.append("")
    lines.append("| 項目 | 內容 |")
    lines.append("|------|------|")
    lines.append(f"| **股票代碼** | {stock_id} |")
    lines.append(f"| **公司名稱** | {company} |")
    lines.append(f"| **最新年度** | {year} |")
    lines.append(f"| **基準 EPS** | {latest_eps:.2f} 元（{base_basis}） |")
    lines.append(f"| **中性 3 分帶** | {neutral_range}（PER 9–10x） |")
    lines.append(
        f"| **目前股價** | {fmt_price(current_price) + ' 元' if current_price is not None else '–'} |"
    )
    lines.append(f"| **中性現價評分** | {current_score_text} |")
    lines.append(f"| **更新日期** | {today} |")
    lines.append("")

    # 財報摘要（年數依實際抓取而定）
    if financial_groups and years:
        lines.append(f"## 近 {len(years)} 年財報摘要")
        lines.append("")
        header = "| 項目 | " + " | ".join(str(y) for y in years) + " | 期間變化 |"
        divider = "|------|" + "------|" * len(years) + "------|"
        for group in financial_groups:
            lines.append(f"### {group['title']}")
            lines.append("")
            lines.append(header)
            lines.append(divider)
            for row in group["rows"]:
                cells = " | ".join(row["values"])
                lines.append(f"| {row['label']} | {cells} | {row['trend']} |")
            lines.append("")

    # 估值情境
    lines.append("## 估值情境（1–5 分價格帶）")
    lines.append("")
    for scenario in report["scenario_rows"]:
        lines.append(f"### {scenario['label']}情境（EPS {scenario['eps']:.2f} 元）")
        lines.append("")
        lines.append("| 分數 | 價格區間 | 對應 PER | 判讀 |")
        lines.append("|------|----------|----------|------|")
        for band in scenario["bands"]:
            score = band["score"]
            lines.append(
                f"| {score} 分 | {band['price_range']} | {per_range_text(band)} | {allocation_for_score(score)} |"
            )
        current = scenario["current_price_view"]
        if current:
            lines.append("")
            lines.append(
                f"> 目前股價 {fmt_price(current['price'])} 元，PER {fmt_per(current['per'])} → **{current['score']} 分**"
            )
        lines.append("")

    # 近年股價位置
    if history:
        lines.append("## 近年股價位置")
        lines.append("")
        lines.append("| 項目 | 內容 |")
        lines.append("|------|------|")
        lines.append(f"| **統計區間** | {history['start_date']}–{history['end_date']}（{history['trading_days']} 個交易日） |")
        lines.append(f"| **收盤區間** | {history['close_low']:.2f}–{history['close_high']:.2f} 元 |")
        lines.append(f"| **最近收盤** | {history['latest_close']:.2f} 元（{history['latest_close_date']}） |")
        lines.append(f"| **區間位置** | {history['range_position_pct']:.2f}%（{history['range_position_label']}） |")
        lines.append(f"| **百分位** | {history['percentile_pct']:.2f}% |")
        lines.append("")

    # 官方／證交所查核連結
    lines.append("## 官方／證交所查核連結")
    lines.append("")
    lines.append(f"- [MOPS 公開資訊觀測站（上市 {stock_id}）](https://mops.twse.com.tw/mops/web/t05st01?step=1&co_id={stock_id}&TYPEK=sii)")
    lines.append(f"- [MOPS 公開資訊觀測站（上櫃 {stock_id}）](https://mops.twse.com.tw/mops/web/t05st01?step=1&co_id={stock_id}&TYPEK=otc)")
    lines.append(f"- [臺灣證券交易所 個股日成交（{stock_id}）](https://www.twse.com.tw/zh/trading/historical/stock-day.html)")
    lines.append(f"- [Yahoo 股市（{stock_id}）](https://tw.stock.yahoo.com/quote/{stock_id}.TW)")
    lines.append(f"- [Goodinfo 個股（{stock_id}）](https://goodinfo.tw/tw/StockInfo/StockDetail.asp?STOCK_ID={stock_id})")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"**最後更新：** {today}")
    lines.append("")
    lines.append("**注**：估值帶依最新年度 EPS 與固定 PER 帶推導，僅為參考；EPS 與股價會隨市場變化，最新資料請點上方連結核對。")
    lines.append("")
    return "\n".join(lines)


def resolve_active_file(vault_root: Path) -> str | None:
    """讀 .obsidian/workspace.json 的 active leaf，回傳相對 vault 的 .md 路徑。"""
    ws = vault_root / ".obsidian" / "workspace.json"
    if not ws.is_file():
        return None
    try:
        data = json.loads(ws.read_text(encoding="utf-8"))
    except Exception:
        return None
    active = data.get("active")
    found: list[str | None] = [None]

    def walk(node: object) -> None:
        if isinstance(node, dict):
            if node.get("type") == "leaf" and node.get("id") == active:
                state = node.get("state", {})
                if state.get("type") == "markdown":
                    found[0] = state.get("state", {}).get("file")
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)

    for key in ("main", "left", "right"):
        walk(data.get(key, {}))
    result = found[0]
    if result and result.endswith(".md"):
        return result
    return None


def unique_path(base: Path) -> Path:
    """若 base 已存在，於檔名尾端加「-2」「-3」…回傳不重複的新路徑。"""
    if not base.exists():
        return base
    stem = base.stem
    n = 2
    while True:
        candidate = base.with_name(f"{stem}-{n}{base.suffix}")
        if not candidate.exists():
            return candidate
        n += 1


def write_obsidian_note(path: Path, content: str, mode: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if mode == "append" and path.exists() and path.stat().st_size > 0:
        lines = content.splitlines()
        count = 0
        body_start = 0
        for index, line in enumerate(lines):
            if line == "---":
                count += 1
                if count == 2:
                    body_start = index + 1
                    break
        body = "\n".join(lines[body_start:]) if count >= 2 else content
        with path.open("a", encoding="utf-8") as handle:
            handle.write("\n" + body.rstrip("\n") + "\n")
    else:
        path.write_text(content if content.endswith("\n") else content + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    analysis_json = args.analysis_json
    if args.stock_id:
        if args.analyze_script is None:
            print(
                "錯誤：提供 --stock-id 時，必須另外提供 --analyze-script。"
                " 目前 repo 沒有預設的 analyze_tw_stock.py，請先確認資料來源或直接提供 --analysis-json",
                file=sys.stderr,
            )
            return 1
        analysis_json = run_analysis(args.stock_id, args.analyze_script)
    if analysis_json is None:
        print("錯誤：請提供 --analysis-json 或 --stock-id", file=sys.stderr)
        return 1

    data = load_analysis_json(analysis_json)
    try:
        base_eps_value, _ = resolve_base_eps(data)
    except ValueError as exc:
        print(f"錯誤：{exc}", file=sys.stderr)
        return 1

    price_history = load_price_history_json(args.price_history_json, data.get("stock_id"))
    scenarios = build_scenarios(args, base_eps_value)
    report = make_report(data, scenarios, args.current_price, price_history)
    if args.output_format == "json":
        rendered_output = json.dumps(report, ensure_ascii=False, indent=2)
    else:  # md
        rendered_output = render_markdown(report)

    # md 且未指定輸出檔／輸出資料夾 → 預設寫入 Obsidian 當前開啟的檔案
    if (
        args.output_format == "md"
        and args.output_file is None
        and args.output_dir is None
    ):
        company = report["company_name"]
        stock_id = report["stock_id"]
        write_mode = args.write_mode
        if write_mode == "newfile":
            # 不動既有檔，改用預設命名建立不重複的新筆記
            # 檔名帶「估值」後綴，與 tw-stock-analysis 的「{代碼}-{名稱}.md」區隔，避免撞名
            output_path = unique_path(args.vault_root / f"{stock_id}-{company}-估值.md")
            target_hint = "建立新檔案"
            write_mode = "overwrite"
        elif args.note_path:
            output_path = args.vault_root / args.note_path
            target_hint = "指定路徑"
        else:
            active_rel = resolve_active_file(args.vault_root)
            if active_rel:
                output_path = args.vault_root / active_rel
                target_hint = "Obsidian 當前開啟檔案"
            else:
                output_path = args.vault_root / f"{stock_id}-{company}-估值.md"
                target_hint = "未偵測到當前檔案，改建新筆記"
        write_obsidian_note(output_path, rendered_output, write_mode)
        print(f"{output_path}（{target_hint}，{args.write_mode}）")
        return 0

    output_path = derive_output_path(
        analysis_json,
        args.output_format,
        args.output_file,
        args.output_dir,
    )
    write_report(output_path, rendered_output)
    print(output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
